server:
  port: 9050

spring:
  application:
   name: QUESTIONSERVICE

  datasource:
    url: "jdbc:postgresql://localhost:5432/quizmanagement"
    username: postgres
    password: postgress

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 