spring:
  application:
    name: EMPLOYEESERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/leavemanagementsystem
    username: postgres
    password: postgress
    driver-class: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9010

