server:
  port: 9191
  
spring:
  application:
    name: "REGISTERSERVICE"

  datasource:
    url: jdbc:postgresql://localhost:5432/streamingservice
    username: postgres
    password: postgress

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
